### profile/:id
GET http://10.171.62.221:3000/profile/8fbde9c9-1e9a-486e-8ca6-6cfb3bef0f78



### user/register 9da9cd24-e696-420b-8d36-97c6970602b5
POST http://10.171.62.221:4242/user/register
Content-Type: application/json

{
    "email": "hired79133@cadinr.com",
    "username": "hired79133",
    "password": "password123",
    "first_name": "123",
    "last_name": "456"
}

###
POST http://10.171.62.221:4242/user/login
Content-Type: application/json

{
    "email": "sogerek126@badgerhole.com",
    "password": "Bobby@123"
}

###
POST http://10.171.62.221:4242/user/forgot-password
Content-Type: application/json

{
    "email": "sogerek126@badgerhole.com"
}

###
POST http://10.171.62.221:4242/user/reset-password
Content-Type: application/json

{
    "token": "81adeb78d6f1e092f3bf1d42d110cfd175fbc7cb006ef1b04538e7d71b67b79c",
    "new_password": "Bobby@123"
}

###
PUT http://10.171.62.221:4242/user/password
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY3MGNhNDdhLWE2YmMtNGM3Ni1hZjg5LTZiODJmOTU0NzI4NyIsImVtYWlsIjoic29nZXJlazEyNkBiYWRnZXJob2xlLmNvbSIsInVzZXJuYW1lIjoiYm9iIiwiaWF0IjoxNzc4NTAxNDUyLCJleHAiOjE3Nzg1ODc4NTJ9.sC35yrk6_lEkkwXtvM1U1g1Z7H1F82gsyMEpyv5l14I
Content-Type: application/json

{
    "current_password": "Bobby@123",
    "new_password": "PoQ456@123"
}

###
GET	http://10.171.62.221:4242/user/profile
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdhNzI4MTQ2LTk2OTktNDU5NS1iN2I1LTcwMDZlNzg3MDgyOCIsImVtYWlsIjoic29nZXJlazEyNkBiYWRnZXJob2xlLmNvbSIsInVzZXJuYW1lIjoic29nZXJlazEyNiIsImlhdCI6MTc3ODQ4NTkwNiwiZXhwIjoxNzc4NTcyMzA2fQ.-I8BT36XA_S9m5fb7xb7Dq_XTBXlhHtEkyLNp3g90W8


###
PUT	http://10.171.62.221:4242/user/profile
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdhNzI4MTQ2LTk2OTktNDU5NS1iN2I1LTcwMDZlNzg3MDgyOCIsImVtYWlsIjoic29nZXJlazEyNkBiYWRnZXJob2xlLmNvbSIsInVzZXJuYW1lIjoic29nZXJlazEyNiIsImlhdCI6MTc3ODQ4NTkwNiwiZXhwIjoxNzc4NTcyMzA2fQ.-I8BT36XA_S9m5fb7xb7Dq_XTBXlhHtEkyLNp3g90W8
Content-Type: application/json

{
    "user": {
        "first_name": "Jack",
        "last_name": "Doe"
    },
    "profile": {
        "gender":"male",
        "sexual_preference":"female",
        "biography":"Hello, I'm John Doe!",
        "latitude": 37.7749,
        "longitude": -122.4194,
        "allow_gps": true
    }
}

###
POST http://10.171.62.221:4242/user/forgot-password
Content-Type: application/json

{
    "email": "sogerek126@badgerhole.com"
}
