### profile/:id
GET http://10.171.62.221:3000/profile/8fbde9c9-1e9a-486e-8ca6-6cfb3bef0f78



### user/register 9da9cd24-e696-420b-8d36-97c6970602b5
POST http://10.171.62.221:3000/user/register
Content-Type: application/json

{
    "email": "hired79133@cadinr.com",
    "username": "hired79133",
    "password": "password123",
    "first_name": "John",
    "last_name": "Doe"
}

### user/login 9da9cd24-e696-420b-8d36-97c6970602b5
POST http://10.171.62.221:3000/user/login
Content-Type: application/json

{
    "email": "tipton.bakary@forliion.com",
    "password": "password123"
}


###
GET	http://10.171.62.221:4242/user/profile
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdhNzI4MTQ2LTk2OTktNDU5NS1iN2I1LTcwMDZlNzg3MDgyOCIsImVtYWlsIjoic29nZXJlazEyNkBiYWRnZXJob2xlLmNvbSIsInVzZXJuYW1lIjoic29nZXJlazEyNiIsImlhdCI6MTc3ODQ4NTkwNiwiZXhwIjoxNzc4NTcyMzA2fQ.-I8BT36XA_S9m5fb7xb7Dq_XTBXlhHtEkyLNp3g90W8


###
PUT	http://10.171.62.221:4242/user/profile
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdhNzI4MTQ2LTk2OTktNDU5NS1iN2I1LTcwMDZlNzg3MDgyOCIsImVtYWlsIjoic29nZXJlazEyNkBiYWRnZXJob2xlLmNvbSIsInVzZXJuYW1lIjoic29nZXJlazEyNiIsImlhdCI6MTc3ODQ4NTkwNiwiZXhwIjoxNzc4NTcyMzA2fQ.-I8BT36XA_S9m5fb7xb7Dq_XTBXlhHtEkyLNp3g90W8
Content-Type: application/json

{
    "user": {
        "first_name": "Jack",
        "last_name": "Doe"
    },
    "profile": {
        "gender":"male",
        "sexual_preference":"female",
        "biography":"Hello, I'm John Doe!",
        "latitude": 37.7749,
        "longitude": -122.4194,
        "allow_gps": true
    }
}